#!/bin/bash
accelerate launch src/train.py \
  --model_name_or_path FacebookAI/xlm-roberta-base \
  --training_data_path data/train.json \
  --testing_data_path data/test.json \
  --max_length 4096 \
  --per_device_train_batch_size 8 \
  --per_device_eval_batch_size 8 \
  --learning_rate 2e-5 \
  --num_train_epochs 1 \
  --output_dir outputs/ \
  --seed 42 \
  --train_top_k 5000 \
  --split \
  --chunk_size 256 \
  --stride 256 \
  --num_chunks1 32 \
  --num_chunks2 8 \
  --maximal_text_length 8192 \
  --weight_decay 0.1 \
  --num_warmup_steps 1000 \
  --pad_last \
  --split_inputs \
  --with_tracking \
  --report_to tensorboard \
  --attention_encoder \
  --sent_length 64 \
  --split_sent
  --predict_test \
  --test_output_file outputs/test_predictions.csv \
  --test_threshold 0.2 \
  --dump_eval_texts
